# Constantes

NUMBERS = '01234567890'

# Definição de tokens

T_INTEGER = 'INTEGER'
T_FLOAT = 'FLOAT'
T_PLUS = 'PLUS'
T_MINUS = 'MINUS'
T_MULTIPLY = 'MULTIPLY'
T_DIVIDE = 'DIVIDE'
T_OPENROUNDBRACKETS = 'OPENROUNDBRACKETS'
T_CLOSEROUNDBRACKETS = 'CLOSEROUNDBRACKETS'
T_EOF = 'EOF'
