# coding=utf-8
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import string
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1366x768")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=768,
    width=1366,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_rectangle(
    0.0,
    0.0,
    1366.0,
    768.0,
    fill="#003554",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    432.5,
    384.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=0
)
def submit():
    code = entry_1.get("1.0", 'end')
    file = open('foo.txt', 'w+')
    file.write(f'{code}')
    file.close()
entry_1.place(
    x=51.0,
    y=36.0,
    width=763.0,
    height=694.0
)
canvas.create_text(
    942.0,
    51.0,
    anchor="nw",
    text="NOSSA LINGUAGEM DE\nPROGRAMAÇÃO",
    fill="#F6F6F6",
    font=("RobotoRoman SemiBold", 32 * -1)
)
canvas.create_rectangle(
    892.0,
    217.0,
    1322.0,
    608.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    1070.0,
    183.0,
    anchor="nw",
    text="Output",
    fill="#FFFFFF",
    font=("RobotoRoman SemiBold", 20 * -1)
)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=submit,
    relief="flat"
)
button_1.place(
    x=998.0,
    y=637.0,
    width=217.0,
    height=50.0
)
canvas.create_text(
    996.0,
    704.0,
    anchor="nw",
    text="Alunos: Marco Barreto, Pedro Wilker, Arthur Calasans",
    fill="#FFFFFF",
    font=("RobotoRoman SemiBold", 10 * -1)
)

window.resizable(False, False)
window.mainloop()
