
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTIPLICATIONDIVISIONDIVISION FLOAT INT MINUS MULTIPLICATION PLUS\n    calc : expression\n         | empty\n    \n    expression : expression MULTIPLICATION expression\n               | expression DIVISION expression\n               | expression PLUS expression\n               | expression MINUS expression\n\n    \n    expression : INT\n               | FLOAT\n    \n    empty :\n    '
    
_lr_action_items = {'INT':([0,6,7,8,9,],[4,4,4,4,4,]),'FLOAT':([0,6,7,8,9,],[5,5,5,5,5,]),'$end':([0,1,2,3,4,5,10,11,12,13,],[-9,0,-1,-2,-7,-8,-3,-4,-5,-6,]),'MULTIPLICATION':([2,4,5,10,11,12,13,],[6,-7,-8,-3,-4,6,6,]),'DIVISION':([2,4,5,10,11,12,13,],[7,-7,-8,-3,-4,7,7,]),'PLUS':([2,4,5,10,11,12,13,],[8,-7,-8,-3,-4,-5,-6,]),'MINUS':([2,4,5,10,11,12,13,],[9,-7,-8,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'expression':([0,6,7,8,9,],[2,10,11,12,13,]),'empty':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> expression','calc',1,'p_calc','calculator.py',55),
  ('calc -> empty','calc',1,'p_calc','calculator.py',56),
  ('expression -> expression MULTIPLICATION expression','expression',3,'p_expression','calculator.py',67),
  ('expression -> expression DIVISION expression','expression',3,'p_expression','calculator.py',68),
  ('expression -> expression PLUS expression','expression',3,'p_expression','calculator.py',69),
  ('expression -> expression MINUS expression','expression',3,'p_expression','calculator.py',70),
  ('expression -> INT','expression',1,'p_int_of_float_expression','calculator.py',85),
  ('expression -> FLOAT','expression',1,'p_int_of_float_expression','calculator.py',86),
  ('empty -> <empty>','empty',0,'p_empty','calculator.py',97),
]
